trigger:
  branches:
    include:
      - main
      - feature/*

parameters:
- name: environment
  displayName: Select Environment
  type: string
  default: dev
  values:
    - dev
    - prod


variables:
  SC: 'ADO-SC-New'
  workDir: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.environment }}'
  tfstateKey: '${{ parameters.environment }}.terraform.tfstate'


stages:
- stage: PreBuildScanning
  displayName: Pre-Build Scanning
  jobs:
    - job:
      displayName: TFLint Scan
      pool: ci agent

      steps:

      - script: |
          cd $(workDir)
          tflint --init
          tflint
        displayName: Run TFLint



- stage: Build
  displayName: Terraform Build
  dependsOn: PreBuildScanning

  jobs:
    - job:
      displayName: Init & Plan
      pool: ci agent

      steps:
      - task: TerraformTask@5
        displayName: Init (reconfigure)
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(workDir)'
          backendServiceArm: '$(SC)'
          backendAzureRmResourceGroupName: 'backend_rg'
          backendAzureRmStorageAccountName: 'adodevpipelinebackend'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: '$(tfstateKey)'

      - task: TerraformTask@5
        displayName: Plan
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(workDir)'
          commandOptions: '-out=tfplan.binary'
          environmentServiceNameAzureRM: '$(SC)'

      - task: PublishPipelineArtifact@1
        displayName: Publish Terraform Plan
        inputs:
          targetPath: '$(workDir)/tfplan.binary'
          artifact: 'terraform-plan'


- stage: SecurityScanning
  displayName: Security Scanning
  dependsOn: Build

  jobs:
    - job:
      displayName: TFsec
      pool: ci agent

      steps:
      - task: tfsec@1
        displayName: Run TFsec
        continueOnError: true
        inputs:
          version: 'v1.26.0'
          dir: '$(workDir)'



- stage: ManualValidation
  displayName: Manual Validation
  dependsOn: SecurityScanning
  condition: eq('${{ parameters.environment }}', 'prod')

  jobs:
    - job:
      displayName: Approval
      pool: server

      steps:
      - task: ManualValidation@1
        displayName: Approval Required
        inputs:
          notifyUsers: 'vishaleva2309@gmail.com'
          approvers: 'vishaleva2309@gmail.com'


- stage: Deploy
  displayName: Terraform Apply
  dependsOn:
    - SecurityScanning
    - ManualValidation

  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

  jobs:
    - job:
      displayName: Apply
      pool: ci agent

      steps:
      - task: TerraformTask@5
        displayName: Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(workDir)'
          backendServiceArm: '$(SC)'
          backendAzureRmResourceGroupName: 'backend_rg'
          backendAzureRmStorageAccountName: 'adodevpipelinebackend'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: '$(tfstateKey)'

      - task: TerraformTask@5
        displayName: Apply
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(workDir)'
          commandOptions: '-auto-approve'
          environmentServiceNameAzureRM: '$(SC)'
